Algoritmo "Area Quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : O Programa multiplica o lado por ele mesmo a fim de encontrar a área
// Data atual  : 01/09/2024
Var
// Seção de Declarações das variáveis
 lado: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um valor dos Lado: ")
leia(lado)
lado <- lado * lado
Escreva("A área do quadrado é: ",lado)
Fimalgoritmo